#!/bin/bash
if [[ ! -e sseutils64.o ]]; then nasm -f elf64 sseutils64.nasm; fi;
nasm -f elf64 fss64omp.nasm
gcc -m64 -msse -O0 -no-pie -fopenmp -sseutils64.o fss64omp.o fss64comp.c -o fss64omp -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./fss64comp $pars
