#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
nasm -f elf32 fss32omp.nasm
gcc -m32 -msse -O0 -no-pie -fopenmp sseutils32.o fss32omp.o fss32comp.c -o fss32omp -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./fss32comp $pars
