#!/bin/bash
if [[ ! -e sseutils32.o ]]; then nasm -f elf32 sseutils32.nasm; fi;
nasm -f elf32 fss32.nasm
gcc -m32 -msse -O0 -no-pie sseutils32.o fss32.o fss32c.c -o fss32c -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./fss32c $pars
