#!/bin/bash
if [[ ! -f sseutils64.nasm ]]; then cp ../../sseutils64.nasm .; fi;
nasm -f elf64 sseutils64.nasm;
for f in $(ls *64omp.nasm); do
	nasm -f elf64 $f;
done;
gcc -m64 -msse -O0 -no-pie -fopenmp sseutils64.o *64omp.o fss64comp.c -o fss64comp -lm
