#!/bin/bash
if [[ ! -f sseutils32.nasm ]]; then cp ../../sseutils32.nasm .; fi;
nasm -f elf32 sseutils32.nasm;
for f in $(ls *32omp.nasm); do
	nasm -f elf32 $f;
done;
gcc -m32 -msse -O0 -no-pie -fopenmp sseutils32.o *32omp.o fss32comp.c -o fss32comp -lm
